name: cradle_hr
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pre-commit
  - pytest
  - python=3.9
  - pandas==1.4.1
  - opencv
  - pip:
    - onnxruntime==1.13.1
    - insightface==0.7.2
    - python-decouple==3.6
