name: cradle_hr
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pre-commit
  - pytest
  - python=3.9
  - pandas
  - pip:
      - opencv-python
      - onnxruntime
      - insightface==0.7.2
      - python-decouple==3.6
